on:
 workflow_dispatch:
  inputs:
   packs:
    description: "packages"

jobs:
 aptest2:
  runs-on: ubuntu-22.04 #also replace at second grep
  steps:
   - name: Run a multi-line script
     run: |
      sudo dpkg --add-architecture i386
      sudo apt update
      a=( ${{ github.event.inputs.packs }} )
      for b in "${a[@]}"; do
       if [ "${b}" != "ovideo:i386" ]; then  #here from "new" not from "additional"
        c=`apt-cache policy $b | grep "^[ ]*500" | head -1 | grep -Poe "(?<=jammy)[^ ]*"`
        echo $b $c
        echo "$c $b" >> file
       fi
      done
      sort -k1nr file >> f
   - name: artifact
     uses: actions/upload-artifact@v4
     with:
      name: file
      path: ./f
