on:
 workflow_dispatch:
jobs:
 tdep:
  runs-on: ubuntu-24.04
  steps:
   - name: Run a multi-line script
     run: |
      curl https://api.github.com/repos/colin-i/ostream/releases/latest -s > 1
      a="`cat 1 | jq '.assets[] | .name'`"
      i=0
      for b in ${a}; do
       b=${b:0-5:4}
       if [ $b = .deb ]; then
        echo ok
        break
       fi
       i=$((i+1))
      done
      b="`cat 1 | jq .assets[${i}].browser_download_url`"
      b=${b:1:-1}
      wget $b -O a.deb

      sudo dpkg --add-architecture i386
      sudo apt update
      sudo apt install -y ./a.deb
