on:
 workflow_dispatch:
  inputs:
   packs:
    description: "packages"

jobs:
 aptest2:
  runs-on: ubuntu-24.04
  steps:
   - name: Run a multi-line script
     run: |
      sudo dpkg --add-architecture i386
      sudo apt update
      a=( ${{ github.event.inputs.packs }} )
      for b in "${a[@]}"; do
       c=`apt-cache policy $b | grep "^[ ]*500" | head -1 | grep -Poe "(?<=noble)[^ ]*"`
       echo $b $c
       echo "$c $b" >> file
      done
      sort -k1nr file >> f
   - name: artifact
     uses: actions/upload-artifact@v4
     with:
      name: file
      path: ./f
