
on:
 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
 ubuild:
  # The type of runner that the job will run on
  runs-on: ubuntu-18.04
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
   - name: Run a multi-line script
     run: |
      name=`cat debian/changelog | head -1 | grep -o ^[^\ ]*`
      echo "proj=${name}" >> $GITHUB_ENV
   - name: Upload Release Asset
     uses: actions/upload-release-asset@v1
     env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
     with:
      upload_url: https://uploads.github.com/repos/colin-i/test/releases/${{ env.up_id }}/assets{?name,label}
      asset_path: ./${{ env.proj }}.zip
      asset_name: ${{ env.proj }}.zip
      asset_content_type: application/zip
