
on:
 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
 ubuild:
  # The type of runner that the job will run on
  runs-on: ubuntu-18.04
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
   #- uses: Bhacaz/checkout-files@master
   #  with:
   #   files: debian/changelog debian/control #is git rev-parse ...
   - uses: actions/checkout@v3
   - name: Run a multi-line script
     run: |
      #proj
      name=`cat debian/changelog | head -1 | grep -o ^[^\ ]*`
      #get up_url
      wget https://github.com/colin-i/test/releases/download/1.5/${name} -O 1.txt
      echo "up_url=`cat 1.txt`" >> $GITHUB_ENV
      #get appimage artifact
      id=$(gh run list --workflow=deb.yml -b $(git rev-parse --abbrev-ref HEAD) | cut -f7 | head -1)
      repo_at_gh=`cat debian/control | grep "^Homepage" | grep -o [^/]*$`
      url=https://api.github.com/repos/colin-i/${repo_at_gh}/actions/artifacts/${id}/zip
      echo ${url}
      curl -L -H "Authorization: token ${{ secrets.PAT }}" ${url} --output a.zip
      #to env
      unzip ./a.zip
      echo "file=${name}.AppImage" >> $GITHUB_ENV
     env:
      #for gh
      GITHUB_TOKEN: ${{ secrets.PAT }}
   - name: Upload Release Asset
     uses: actions/upload-release-asset@v1
     env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
     with:
      upload_url: ${{ env.up_url }}
      asset_path: ./${{ env.file }}
      asset_name: ${{ env.file }}
      asset_content_type: application/x-executable
